### ISSUE TITLE
Issue with Error message stating inputs are of wrong sizes

### ISSUE THREAD

**Issue by swzCuroverse** [EpistasisLab/scikit-rebate#48]
I am getting the following error,  my inputs are of the correct input size. I am not sure where to contact the authors for assistance so writing this up as an issue.  Xtrain is all ones and zeros (it comes from a 1hot encoder) and y is all ones and zeros.   Example code given in documentation works fine so not an install issue.

I used the following code (I am running on a 16 core machine):
fs = ReliefF(n_features_to_select=2000, n_neighbors=100,n_jobs=-1)
fs.fit(Xtrain, y)

Shapes for additional info:
>>> y.shape
(3672,)
>>> Xtrain.shape
(3672, 1688789)

Error message:
Traceback (most recent call last):
  File "reliefChr19.py", line 180, in <module>
    fs.fit(Xtrain, y)
  File "/usr/local/lib/python2.7/dist-packages/skrebate/relieff.py", line 154, in fit
    self.attr = self._get_attribute_info() #Examines each feature and applies discrete_threshold to determine variable type.
  File "/usr/local/lib/python2.7/dist-packages/skrebate/relieff.py", line 280, in _get_attribute_info
    zlen = len(np.unique(z))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/arraysetops.py", line 210, in unique
    return _unique1d(ar, return_index, return_inverse, return_counts)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/arraysetops.py", line 279, in _unique1d
    flag = np.concatenate(([True], aux[1:] != aux[:-1]))
ValueError: all the input arrays must have same number of dimensions

**Comment by ryanurbs** [comment]
were you able to figure out this issue?

**Comment by swzCuroverse** [comment]
No, I have not.  However, I know have a set of data that we can use that is public so I can give it to you for debugging purposes.  I will write up a script in the next few days if that is useful?

**Comment by weixuanfu** [comment]
A script for reproducing this issue is helpful. Thank you!

One questions, what is `type(Xtrain)` in your codes?

**Comment by ryanurbs** [comment]
Yeah i'm just trying to figure out if there is a bug that needs to be fixed or if there might be a user error issue. Last night we just released a new version with a number of updates/fixes. So perhaps that alone might resolve your issue.

**Comment by swzCuroverse** [comment]
Ok, I will update the version and try again.

**Comment by swzCuroverse** [comment]
Xtrain was a sparse that I made using the 1-hot encoding in sci-kit learn that I convert to dense using Xtrain = Xtrain.todense(),

**Comment by swzCuroverse** [comment]
I updated and it seems to be chugging away with no error, so a good sign!
